# Generated by Django 4.2 on 2023-04-17 21:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("image_1", models.ImageField(blank=True, upload_to="uploads/")),
                ("image_2", models.ImageField(blank=True, upload_to="uploads/")),
                ("image_3", models.ImageField(blank=True, upload_to="uploads/")),
            ],
        ),
    ]
